export type Employment = { title: string; employer: string; dates?: string; bullets: string[] };
export type Recommendation = { id: string; title: string; detail: string; kind: string; proposed?: string };
export type ApplicationQuestion = {
  id: string;
  prompt: string;
  kind: string;
  answer: string;
  blankReason?: string;
  hint?: string;
  source?: string;
};
export type AccountJob = {
  id: string;
  title: string;
  company: string;
  applyCompany: string;
  viaCompany: string;
  sourceName: string;
  primaryUrl: string;
  location: string;
  remoteType: string;
  salaryMin: number | null;
  salaryMax: number | null;
  category: string;
  verification: string;
  description: string;
  score: number;
  label: string;
  explanation: string;
  matched: string[];
  missing: string[];
  preferredMatched: string[];
  explanationLocked?: boolean;
  applied: boolean;
};
export type AccountData = {
  profile: {
    headline: string;
    summary: string;
    skills: string[];
    employment: Employment[];
    education: string[];
    preferences: {
      salary?: string;
      workArrangement?: string;
      locations?: string;
      workAuthorization?: string;
      excludeCompanies?: string;
      excludeKeywords?: string;
    };
    resumeName: string;
    photoUrl: string;
    slug: string;
    city: string;
    address: string;
    shareContact: boolean;
  } | null;
  plan: { id: string; name: string; monthlyCents: number; yearlyCents: number };
  features: Record<string, boolean | number>;
  policy: { allowUpgrade: boolean; allowDowngrade: boolean; allowProration: boolean; allowRefund: boolean };
  plans: { id: string; name: string; blurb: string; monthlyCents: number; yearlyCents: number; popular: boolean }[];
  gateways: { id: string; name: string; kind: string }[];
  autoApply: boolean;
  autoMin: number;
  autoDailyCap: number;
  autoCapUsed: number;
  autoApplyAuthorization?: {
    version: string;
    text: string;
    authorized: boolean;
    authorizedAt: number | null;
    currentVersion?: string | null;
  };
  billingDisclosure?: {
    version: string;
    text: string;
    accepted: boolean;
    acceptedAt: number | null;
    currentVersion?: string | null;
  };
  media?: {
    serverCount: number;
    hasTurn: boolean;
    hasStun: boolean;
    productionReady: boolean;
  };
  matchQuota?: {
    limit: number;
    used: number;
    remaining: number | null;
    unlimited: boolean;
    resetsAt: number;
  };
  reviewQuota?: {
    limit: number;
    used: number;
    remaining: number | null;
    unlimited: boolean;
    resetsAt: number;
  };
  statuses: string[];
  stats: {
    resumeRating: number | null;
    applied: number;
    tracked: number;
    ready: number;
    reviewRequired: number;
    responded: number;
    available: number;
    recommended: number;
    versions: number;
    kitOpened?: number;
    kitCompleted?: number;
    kitCompletionRate?: number;
    followUpsDue?: number;
    followUpsOpen?: number;
  };
  jobs: AccountJob[];
  applications: {
    id: string;
    title: string;
    company: string;
    viaCompany: string;
    sourceName: string;
    targetUrl: string;
    delivery: string;
    status: string;
    mode: string;
    match: number;
    versionId?: string;
    versionLabel?: string;
    questions?: ApplicationQuestion[];
  }[];
  review: { id: string; rating: number; feedback: string[]; recommendations: Recommendation[] } | null;
  versions: { id: string; label: string; kind: string; active: boolean; rendered: string }[];
  template: string;
  templateLimit: number;
  templates: { id: string; name: string; detail: string }[];
};

export type ResumeView = {
  name: string;
  headline: string;
  summary: string;
  skills: string[];
  employment: { title?: string; employer?: string; dates?: string; bullets?: string[] }[];
  education: string[];
  photoUrl: string;
  city: string;
  email: string;
  phone: string;
  template: string;
};
